---
title: "JSC370 Final Project HW5"
# author: "Tsai-Ni Lin"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my JSC370 Final Project website.

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(cache=TRUE, echo=FALSE, warning = FALSE, message = FALSE)
```


```{r,echo=FALSE}
library(data.table)
library(tidyverse)
library(plotly)
library(knitr)
library(widgetframe)
library(dplyr)
```

```{r}
data <- readRDS('midterm_data.rds')
```




```{r}

#records after 2010
country_records2 <- data %>%  filter(Year >= 2010) %>% group_by(Country) %>% mutate(record_count = n())

#maximum amount of time country was reported
max_count <- max(country_records2$record_count)

#filter out countries that don't appear for "max count of times"  after 2010
freq_countries <- country_records2 %>% filter(record_count >= max_count) 


#yearly mean happiness in selected countries
main_plt_data <- freq_countries %>% group_by(Year) %>%summarise(mean_happiness = mean(Happiness), level = "Overall", n=n())


#mean of gdp, sunshine, and freedom
mean_gdp = mean(freq_countries$Log_GDP)
mean_sunshine = mean(freq_countries$Avg_sunshine)
mean_freedom = mean(freq_countries$Freedom)

#create income category 
levels_countries_income <- freq_countries %>% mutate(level = case_when(Log_GDP >= mean_gdp 
                                                   ~ "Income Above Average", TRUE ~"Income Below Average" )) 

#calculate the mean happiness in each year by income category
plt_income <- levels_countries_income %>% group_by(Year, level) %>% summarise(mean_happiness = mean(Happiness), n=n())



#create sunshine category 
levels_countries_sunshine <- freq_countries %>% mutate(level = case_when(Avg_sunshine >= mean_sunshine 
                                                   ~ "Sunshine Above Average", TRUE ~"Sunshine Below Average" )) 



#calculate the mean happiness score in each year by sunshine category
plt_sunshine <- levels_countries_sunshine %>% group_by(Year, level) %>% summarise(mean_happiness = mean(Happiness), n=n())



# create freedom category
levels_countries_freedom <- freq_countries %>% mutate(level = case_when(Freedom >= mean_freedom 
                                                   ~ "Freedom Above Average", TRUE ~"Freedom Below Average" )) 

#calculate the mean happiness score in each year by freedom category
plt_freedom <- levels_countries_freedom %>% group_by(Year, level) %>% summarise(mean_happiness = mean(Happiness), n=n())


#combine the data frames
time_plot <- bind_rows(plt_income, plt_sunshine, plt_freedom, main_plt_data)

```


```{r}
#plot time series plot
 p2 <- ggplot(data=time_plot, aes(x=Year,y = mean_happiness, color = level)) +
geom_line() + 
  geom_point(data=time_plot, aes(x=Year,y = mean_happiness, text= paste("Year: ", Year, "<br>", 
                                    "Mean Happiness Score: ", round(mean_happiness,3), "<br>",
                                    "Level:", level, "<br>", sep = " "
                                    ))) + guides(fill=guide_legend(title="Country Category")) + 
   labs(y = "Mean Happiness Score", x = "Year", title = "Mean Happiness Score Overtime for Countries recorded every year bewteen 2010-2020") + theme(plot.title = element_text(size=10))

#adjust x-axis scales
 p2 <- p2+ 
scale_x_continuous(breaks= c(2010, 2015, 2020))
 
```

```{r}
sum <- data%>% group_by(Country) %>% mutate(avg_gdp = mean(Log_GDP), avg_freedom = mean(Freedom)) 

mean_freedom <- mean(data$Freedom)
sum <- sum %>% mutate(freedom_level = case_when(Freedom >= mean_freedom 
                                                   ~ "Freedom Above Average", TRUE ~"Freedom Below Average"))
```



```{r}
plt_smooth1 <- ggplot(
  sum, 
  aes(x = Log_GDP, y= Happiness,text= paste("Country: ", Country, "<br>", 
                                    "Log GDP: ", round(Log_GDP,3), "<br>",
                                    "Happiness Score: ", round(Happiness,3)))) + 
  theme_minimal() + 
  geom_smooth(inherit.aes = FALSE, aes(x = Log_GDP, y= Happiness)) + 
  geom_point(aes(colour = Country),alpha = 4/10) + 
labs(x = "Log GDP", y = "Happiness Score", title = "Happiness Score vs. Log GDP by Country")


```


```{r}
plt_smooth2 <- ggplot(
  sum, 
  aes(x = Freedom, y= Happiness,text= paste("Country: ", Country, "<br>", 
                                    "Freedom Score: ", round(Freedom,3), "<br>",
                                    "Happiness Score: ", round(Happiness,3)))) + 
  theme_minimal() + 
  geom_smooth(inherit.aes = FALSE, aes(x = Freedom, y= Happiness)) + 
  geom_point(aes(colour = Country),alpha = 4/10) + 
labs(x = "Log GDP", y = "Happiness Score", title = " Happiness Score vs. Freedom Score by Country")
```



```{r}
# par(mfrow = c(2, 2))
# plt <- ggplot(data, aes(x=Log_GDP)) + geom_histogram()
# 
plt1 <- ggplot(data, aes(x=Log_GDP)) + geom_histogram() + labs(xlab = 'Log GDP per Capita', title = 'Distribution of Log GDP per Capita')

plt2 <- ggplot(data, aes(x=Avg_sunshine)) + geom_histogram() + labs(xlab = 'Log GDP per Capita', title = 'Distribution of Yearly Sunshine Hours (hrs)')

plt3 <- ggplot(data, aes(x=Freedom)) + geom_histogram() + labs(xlab = 'Log GDP per Capita', title = 'Distribution of Freedom Score')

plt4 <- ggplot(data, aes(x=Happiness)) + geom_histogram() + labs(xlab = 'Log GDP per Capita', title = 'Distribution of Happiness Score')

```


```{r}
#create income level
data3 <- data %>% mutate(income_level = case_when((Log_GDP <= 
                                                   quantile(Log_GDP, probs =0.25, na.rm = TRUE)) ~ "Low",
                                                 (quantile(Log_GDP, probs =0.25, na.rm = TRUE) < Log_GDP & Log_GDP<= 
                                                   quantile(Log_GDP, probs =0.75, na.rm = TRUE)) ~ "Medium",
                                                TRUE ~ "High"))


#create sunshine level
data3 <- data3 %>% mutate(sunshine_level = case_when((Avg_sunshine < 
                                                   quantile(data$Avg_sunshine, probs =0.5, na.rm = TRUE)) ~ "Low Sunshine Level",TRUE ~ "High Sunshine Level"))


#create freedom level
data3 <- data3 %>% mutate(freedom_level = case_when((Freedom < 
                                                   quantile(data$Freedom, probs =0.5, na.rm = TRUE)) ~ "Low Freedom Level",TRUE ~ "High Freedom Level"))

```
```{r}
#income level plt                                              
l1 <- ggplot(data = data3, mapping = aes(x = income_level, y = Happiness)) + 
geom_boxplot(fill="pink")+ labs(x = "Income Level", y= "Happiness Score") 

#sunshine_level plt                                              
l2 <- ggplot(data = data3, mapping = aes(x = sunshine_level, y = Happiness)) + 
geom_boxplot(fill="mediumpurple1") + labs(x = "Sunshine Level", y= "Happiness Score") + scale_x_discrete(labels=c("High Sunshine Level" = "High", "Low Sunshine Level" = "Low"))


#freedom level plt                                              
l3 <- ggplot(data = data3, mapping = aes(x = freedom_level, y = Happiness)) + 
geom_boxplot(fill="lavenderblush1") + labs(x = "Freedom Level", y= "Happiness Score") + scale_x_discrete(labels=c("High Freedom Level" = "High", "Low Freedom Level" = "Low"))


# #combine the three plots
# ggarrange(l1, l2, l3, 
#           ncol = 2, nrow = 2) + labs(title = "Distribution of Happiness Score based on Sunshine Level, Freedom Level, and Income Level (Individually)")+ theme(plot.title = element_text(size=10)) 
```







## Happiness Score Overtime 

```{r echo=FALSE}
ggplotly(p2, tooltip = "text")
```

## Happiness Score vs. Predictors {.tabset} 

### Log GDP

```{r}
ggplotly(plt_smooth1, tooltip = "text")
```
### Freedom Score

```{r}
ggplotly(plt_smooth2, tooltip = "text")
```

{-}


## Happiness Based on Levels {.tabset}


### Income Level

```{r}
ggplotly(l1)
```

### Sunshine Level


```{r}
ggplotly(l2)
```

### Freedom Level

```{r}
ggplotly(l3)
```




{-}

